backend:
  name: github
  repo: Symptom7489/dpec-test

media_folder: images/members
public_folder: /images/members

collections:
  - name: "members"
    label: "Members"
    folder: "members"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Pronouns", name: "pronouns", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "body", widget: "markdown" }
